- iOS/MDL/MDL/GPU/Loader.swift
- iOS/MDL/MDL/GPU/Matrix.swift
matrix method typo error , cout should be count
> fix typo error

- src/layer/pooling_layer.cpp
reference: https://github.com/BVLC/caffe/blob/master/src/caffe/layers/pooling_layer.cpp#L201
> sum's divisor should include those padding areas

- build.sh
- include/commons/commons.h
build successfully on my Ubuntu.
main changes : 
build.sh add    DCMAKE_EXE_LINKER_FLAGS  (lpthread)
commons.h  add #include <string.h> #include <limits.h>
> build for linux(ubuntu)

- fluid/CMakeLists.txt
- fluid/src/framework/program.h
- fluid/src/io.cc
- fluid/src/io.h
- fluid/test/main.cc
fix #130 add paddle mobile test
> fix #130 add paddle mobile test

- .clang_format.hook
- .pre-commit-config.yaml
- .travis.yml
- .travis/check_style.sh
- fluid/.clang-format
- fluid/README.md
- fluid/src/framework/program.h
- fluid/src/io.cc
- fluid/src/io.h
- fluid/src/operators/operator.cc
- fluid/src/operators/operator.h
- fluid/test/main.cc
> Add the use of pre-commit to check style and travis CI.

- src/framework/operator.h
- src/operators/elementwise_add_op.h
fix Run() instead of RunImp() in elementwise_add_op
> fix #181 Run() in elementwise_add_op.h

- src/io.cpp
- test/elementwise_add_op_test.h
- test/mul_op_test.h
elementwise_add_op_test
mul_op_test
> fix #191 use LOG instead of cout

- src/common/type_define.h
- src/framework/op_info.h
- src/framework/op_registry.h
- src/framework/operator.h
- src/operators/conv_op.cpp
> add op registry

- src/operators/box_coder_op.cpp
- src/operators/box_coder_op.h
- src/operators/kernel/arm/box_coder_kernel.cpp
- src/operators/kernel/arm/concat_kernel.cpp
- src/operators/kernel/arm/prior_box_kernel.cpp
- src/operators/kernel/box_coder_kernel.h
- src/operators/op_param.h
- test/CMakeLists.txt
- test/operators/test_box_coder_op.cpp
generate n* 1917 * 4 target (predict) boxes in local SSD model.
> fix #225 add box_coder and test

- src/operators/math/Gemm.cpp
- src/operators/math/Gemm.h
- test/CMakeLists.txt
- test/common/test_gemm.cpp.cpp
> add Gemm library

- src/framework/data_transform.cpp
- src/framework/data_transform.h
- src/framework/data_type.h
- src/framework/op_info.h
- src/framework/op_kernel_type.h
- src/framework/op_proto_maker.h
- src/framework/op_registry.h
- src/framework/operator.cpp
- src/framework/operator.h
- src/operators/kernel/arm/conv_kernel.cpp
- src/operators/math/im2col.cc
- src/operators/math/im2col.h
- src/operators/math/math_function.cc
- src/operators/math/math_function.h
- src/operators/math/vol2col.cc
- src/operators/math/vol2col.h
- test/common/test_gemm.cpp.cpp
> add copyright

- src/framework/op_info.h
- src/framework/op_registry.h
- src/operators/math/softmax.cpp
- test/executor_for_test.h
> update op registry

- src/operators/kernel/arm/conv_kernel.cpp
> update conv op kernel

- README.md
- build.sh
> fix ubuntu compile

- src/operators/math/gemm.cpp
- src/operators/math/gemm.h
- test/common/test_gemm.cpp.cpp
> update Gemm with implementation of 'C = alpha * A * B + beta * C'

- src/framework/op_registry.h
- src/io.cpp
- src/operators/kernel/arm/conv_kernel.cpp
- test/executor_for_test.h
- test/operators/test_sigmoid_op.cpp
- test/operators/test_softmax_op.cpp
> refine unit test

- src/framework/operator.cpp
- test/executor_for_test.h
> Init tensor memory in executor_for_test

- src/operators/depthwise_conv_op.cpp
- src/operators/depthwise_conv_op.h
- src/operators/kernel/arm/depthwise_conv_kernel.cpp
- src/operators/kernel/depthwise_conv_kernel.h
- test/CMakeLists.txt
- test/operators/test_depthwise_conv_op.cpp
> submit depthwise_conv_op and test

- CMakeLists.txt
- scripts/push2android.sh
- src/common/enforce.h
- src/framework/operator.cpp
- src/framework/operator.h
- src/io.cpp
- src/io.h
- src/operators/math/softmax.cpp
- test/net/test_googlenet.cpp
- test/net/test_mobilenet.cpp
add an interface with  tensor as output
> add impl for executor'predict

- src/framework/operator.cpp
> fix compile error on ubuntu

- build.sh
Fix https://github.com/PaddlePaddle/paddle-mobile/issues/337
> Remove unused code in build.sh

- CMakeLists.txt
Fix https://github.com/PaddlePaddle/paddle-mobile/issues/339
> Remove unused third-party dependencies

- CMakeLists.txt
- src/operators/math/gemm.cpp
> update gemm with neon assembly

- tools/scripts/push2android.sh
> Move /scripts to /tools

- CMakeLists.txt
> use a macro to control whether use std::exception

- src/io/io.cpp
add profile to debug log 'op_type cpu_tick percentage'
```
DEBUG   [file: io.cpp] [line: 358] : ========================[ profile ]==========================
DEBUG   [file: io.cpp] [line: 364] : batch_norm      	90		2.14848
DEBUG   [file: io.cpp] [line: 364] : box_coder       	85		2.02912
DEBUG   [file: io.cpp] [line: 364] : concat          	144		3.43757
DEBUG   [file: io.cpp] [line: 364] : conv2d          	87		2.07687
DEBUG   [file: io.cpp] [line: 364] : depthwise_conv2d	2708		64.6455
DEBUG   [file: io.cpp] [line: 364] : elementwise_add 	25		0.596801
DEBUG   [file: io.cpp] [line: 364] : feed            	68		1.6233
DEBUG   [file: io.cpp] [line: 364] : fetch           	13		0.310337
DEBUG   [file: io.cpp] [line: 364] : multiclass_nms  	97		2.31559
DEBUG   [file: io.cpp] [line: 364] : …
```
> #402 add profile info

- src/framework/op_registry.h
> simplify op registry

- src/operators/kernel/arm/depthwise_conv_kernel.cpp
- src/operators/math/gemm.cpp
- src/operators/math/gemm.h
> optimize gemm

- src/operators/kernel/arm/conv_add_kernel.cpp
- src/operators/kernel/arm/conv_kernel.cpp
- src/operators/kernel/arm/pool_kernel.cpp
- src/operators/math/pool_2x2.cpp
- src/operators/math/pool_2x2.h
- src/operators/math/pool_3x3.cpp
- src/operators/math/pool_3x3.h
- src/operators/math/pooling.cpp
- src/operators/math/pooling.h
> optimize pool kernel

- src/operators/kernel/arm/conv_add_kernel.cpp
- src/operators/kernel/conv_add_kernel.h
> optimize conv-add kernel with neon intrinsics

- src/operators/math/gemm.cpp
> add 'pld' instruction in Gemm

- src/memory/t_malloc.cpp
- src/operators/math/gemm.cpp
- src/operators/math/gemm.h
> add vector matrix multiplication in Gemm

- src/operators/math/gemm.cpp
- test/common/test_gemm.cpp
> optimize gemm code

- src/operators/math/gemm.cpp
- src/operators/math/gemm.h
> optimize gemm performance

- CMakeLists.txt
- demo/android/PaddleMobile_Android/app/src/main/java/com/baidu/paddle/MainActivity.java
- demo/android/PaddleMobile_Android/app/src/main/java/com/baidu/paddle/PML.java
- src/jni/paddle_mobile_jni.cpp
- src/jni/paddle_mobile_jni.h
> add jni interface to load combined model&params

- src/operators/math/gemm.cpp
- src/operators/math/gemm.h
- src/operators/math/math_function.cpp
- src/operators/math/math_function.h
> Optimize Gemm: fuse add relu batchnorm op, dynamic block, add AddDot4x8, optimize memory write back.

- src/operators/math/gemm.cpp
> update gemm with batchnrom fusion

- metal/paddle-mobile/paddle-mobile/Operators/BatchNormOp.swift
- metal/paddle-mobile/paddle-mobile/Operators/Kernels/BatchNormKernel.swift
- metal/paddle-mobile/paddle-mobile/Operators/Kernels/Kernels.metal
> #545 batch norm

- CMakeLists.txt
- src/io/executor.cpp
- src/io/executor.h
- src/operators/kernel/central-arm-func/conv_add_arm_func.h
- src/operators/kernel/lrn_kernel.h
- src/operators/math/gemm.cpp
- src/operators/math/gemm.h
- src/operators/math/math_function.cpp
- src/operators/math/pool_3x3.cpp
- src/operators/math/pool_3x3.h
- src/operators/math/pooling.cpp
- test/net/test_googlenet.cpp
> Revert: accelerate with openmp

- src/operators/math/gemm.cpp
> fix gemm assembly bug while compile with clang of NDK17

- demo/android/PaddleMobile_Android/app/src/main/java/com/baidu/paddle/MainActivity.java
- demo/android/PaddleMobile_Android/app/src/main/java/com/baidu/paddle/PML.java
- doc/development_doc.md
- src/jni/paddle_mobile_jni.cpp
- src/jni/paddle_mobile_jni.h
- src/operators/math/pooling.cpp
> add jni interface to accept yuv420 as input

- doc/development_doc.md
> fix linux compile error

- src/io/executor.cpp
- src/io/executor.h
- src/io/paddle_mobile.cpp
- src/io/paddle_mobile.h
- test/net/test_googlenet.cpp
> add interface to dynamic set omp thread num

- src/operators/math/gemm.cpp
- test/net/test_mobilenet.cpp
> add openmp in gemm and test_mobilenet

- CMakeLists.txt
> upgrade minimum cmake version to 3.6

- CMakeLists.txt
- src/operators/math/depthwise_conv_3x3.cpp
- src/operators/math/gemm.cpp
- tools/ios-cmake/ios.toolchain.cmake
> add macro definition:__ARM_NEON, __aarch64__

- src/operators/math/gemm.cpp
- src/operators/math/gemm.h
> fix android cross-compilation on armv8 platform

- tools/build.sh
- tools/ios-cmake/ios.toolchain.cmake
> add choice of ios target platform

- CMakeLists.txt
- src/framework/program/program.h
- src/io/executor.cpp
- src/io/loader.cpp
- src/io/loader.h
- src/io/paddle_mobile.cpp
- src/io/paddle_mobile.h
- test/net/test_googlenet.cpp
- tools/quantification/CMakeLists.txt
- tools/quantification/convert.cpp
> add quantification tool to compress binary size

- src/common/types.cpp
- src/common/types.h
update FPGA ops declaration in types h and cpp file
> update FPGA ops declaration in types h and cpp file

- test_gemm.cpp
fix test_gemm.c to check sgemmwithbn
> issue #658, fix test_gemm.c to check sgemmwithbn

- src/common/types.h
- src/framework/program/program-optimize/fusion_op_register.h
- src/framework/tensor.h
- src/io/executor.cpp
- src/operators/concat_op.cpp
- src/operators/concat_op.h
- src/operators/kernel/fpga/concat_kernel.cpp
- tools/android-cmake/android.toolchain.cmake
- tools/build.sh
> created fpga concat op:#647

- src/operators/math/gemm.cpp
- src/operators/math/gemm.h
> add armv8 version of gemm

- test/net/test_mobilenet+ssd.cpp
- test/net/test_mobilenet.cpp
> update unit test of mobilenet and mobilenetssd

- src/framework/tensor.h
Otherwise a warning appears for "input->fpga_args().scale_pointer();"
> add const attribute. close #689

- CMakeLists.txt
- src/framework/tensor.h
- src/operators/kernel/fpga/fc_relu_kernel.cpp
- src/operators/kernel/fpga/fusion_fc_kernel.cpp
solve the problem that * convert to const *
> update tensor.h file closed #702

- src/io/api.cc
- src/io/api_paddle_mobile.cc
- src/io/api_paddle_mobile.h
- src/io/paddle_inference_api.h
- test/CMakeLists.txt
- test/framework/test_inference_api.cpp
> add high api for paddle mobile

- src/operators/kernel/central-arm-func/conv_add_arm_func.h
- src/operators/kernel/central-arm-func/conv_add_relu_arm_func.h
- src/operators/kernel/central-arm-func/conv_arm_func.h
- src/operators/kernel/central-arm-func/fusion_fc_arm_func.h
- src/operators/kernel/central-arm-func/mul_arm_func.h
- src/operators/math/gemm.cpp
- src/operators/math/gemm.h
- src/operators/math/math_function.cpp
- src/operators/math/math_function.h
- test/common/test_gemm_perf.cpp
> add gemm merge function: C = A * B + bias

- src/common/enforce.h
- src/operators/kernel/central-arm-func/conv_add_relu_arm_func.h
- src/operators/kernel/central-arm-func/conv_arm_func.h
- src/operators/kernel/central-arm-func/fusion_fc_arm_func.h
- src/operators/kernel/central-arm-func/mul_arm_func.h
- src/operators/math/gemm.cpp
> update enforce rule

- src/operators/feed_op.h
- src/operators/fetch_op.cpp
- src/operators/fetch_op.h
Register FeedOp and FetchOp for FPGA track
> register Feed and Fetch ops. Close #714

- src/operators/math/gemm.cpp
> add empty function in Gemm for compilation of other platform

- src/operators/math/depthwise_conv_3x3.cpp
> implement multithreading 3x3 s1 depthwise_conv

- src/operators/math/depthwise_conv_3x3.cpp
> optimize multithreading 3x3 s2 depthwise_conv

- src/jni/PML.java
- src/jni/paddle_mobile_jni.cpp
- src/jni/paddle_mobile_jni.h
update jni with lock and exception logics && add java interface close #807
> update jni with lock and exception logics && add java interface close #807

- src/operators/feed_op.h
To make the log information perfect.
> Assign value for scale pointer. close #810

- src/jni/paddle_mobile_jni.cpp
- src/operators/math/gemm.cpp
- test/net/test_googlenet.cpp
- test/net/test_mobilenet+ssd.cpp
- test/net/test_mobilenet.cpp
- test/net/test_squeezenet.cpp
- test/net/test_yolo.cpp
> update unit test and jni

- test/net/test_googlenet.cpp
- test/net/test_mobilenet+ssd.cpp
- test/net/test_mobilenet.cpp
- test/net/test_mobilenet_combine.cpp
- test/net/test_resnet.cpp
- test/net/test_squeezenet.cpp
- test/net/test_yolo.cpp
> fix annotation of unit test of net

- metal/paddle-mobile/paddle-mobile.xcodeproj/project.pbxproj
- metal/paddle-mobile/paddle-mobile.xcodeproj/project.xcworkspace/xcuserdata/zhangxinjun.xcuserdatad/IDEFindNavigatorScopes.plist
- metal/paddle-mobile/paddle-mobile.xcodeproj/xcuserdata/zhangxinjun.xcuserdatad/xcschemes/xcschememanagement.plist
- metal/paddle-mobile/paddle-mobile/Common/PaddleMobileUnitTest.swift
- metal/paddle-mobile/paddle-mobile/Executor.swift
- metal/paddle-mobile/paddle-mobile/Operators/Base/OpCreator.swift
- metal/paddle-mobile/paddle-mobile/Operators/Base/Operator.swift
- metal/paddle-mobile/paddle-mobile/Operators/BatchNormReluOp.swift
- metal/paddle-mobile/paddle-mobile/Operators/CNNConvAddBatchNormReluOp.swift
- metal/paddle-mobile/paddle-mobile/Operators/ConvAddBatchNormReluOp.swift
- metal/paddle-mobile/paddle-mobile/Operators/Kernels/BatchNormRelu.metal
- metal/paddle-mobile/paddle-mobile/Operators/Kernels/BatchNormReluKernel.swift
- metal/paddle-mobile/paddle-mobile/Operators/Kernels/CNNConvKernel.swift
- metal/paddle-mobile/paddle-mobile/Operators/Kernels/ConvAddBatchNormReluKernel.swift
- metal/paddle-mobile/paddle-mobile/Operators/Kernels/ConvAddKernel.swift
- metal/paddle-mobile/paddle-mobile/framework/Texture.swift
> add MPS API

- src/operators/kernel/central-arm-func/conv_transpose_arm_func.h
> repair bug of  predict ten times' diffent result in genet

- src/operators/math/im2col.cpp
> fix im2col in case of 2*2 input

- src/operators/math/gemm.cpp
> repair bug of bias is nullptr

- src/operators/math/gemm.cpp
> separate C = A * B + bias and C = A * B + C in Gemm

- src/framework/operator.cpp
- src/framework/tensor.h
- src/operators/concat_op.cpp
- src/operators/crf_op.cpp
- src/operators/fusion_fc_op.cpp
- src/operators/gru_op.cpp
- src/operators/kernel/arm/concat_kernel.cpp
- src/operators/kernel/arm/fusion_fc_kernel.cpp
- src/operators/kernel/arm/gru_kernel.cpp
- src/operators/kernel/arm/lookup_kernel.cpp
- src/operators/kernel/central-arm-func/crf_arm_func.h
- src/operators/kernel/central-arm-func/gru_arm_func.h
- src/operators/lookup_op.cpp
- test/net/test_nlp.cpp
> three ops, model run passed

- src/operators/kernel/central-arm-func/gru_arm_func.h
> fix some bugs

- src/operators/kernel/central-arm-func/conv_transpose_arm_func.h
- src/operators/math/im2col.cpp
> update the structure of the code of im2col.cpp

- src/operators/math/gemm.cpp
> fix PRelu merge operation in Gemm

- src/operators/math/gemm.cpp
- src/operators/math/math_function.cpp
> add border check in gemm

- CMakeLists.txt
- src/operators/math/gemm.cpp
> fix compilation problems

- src/operators/math/pool_3x3.cpp
> repair bug of pool3x3

- src/operators/math/im2col.cpp
> repair bug of im2col

- src/operators/math/math_function.cpp
> imp conv_transpose op

- src/framework/operator.cpp
- src/operators/kernel/central-arm-func/prior_box_arm_func.h
- src/operators/op_param.h
- test/net/test_mobilenet_025_fssd.cpp
- test/test_helper.h
add new attr in pribox to suite fssd  close #924
> add new attr in pribox to suite fssd  close #924

- src/framework/operator.cpp
suit multi inputs and out put . and fix bug when isInitialized check close #964
> suit multi inputs and out put . and fix bug when isInitialized check close #964

- src/operators/op_param.h
> FusionConvXXXParam inheritance ConvParam

- test/framework/test_load.cpp
remove git-conflict mark from test_load.cpp file
> remove git-conflict mark

- src/operators/fetch_op.h
- src/operators/kernel/cl/batchnorm_kernel.cpp
- src/operators/kernel/cl/fetch_kernel.cpp
- src/operators/kernel/cl/pool_kernel.cpp
- src/operators/kernel/fetch_kernel.h
> add cl kernel

- src/operators/math/gemm.cpp
- src/operators/math/gemm.h
- src/operators/math/gru_compute.cpp
- src/operators/math/math_function.cpp
- test/CMakeLists.txt
- test/common/test_gemm_accuracy.cpp
- test/net/test_multi_inference_predict.cpp
trans gemm to class && add multi instance support && to unit test  solved #1080
> trans gemm to class && add multi instance support && to unit test

- CMakeLists.txt
> open -fembed-bitcode option for ios

- src/operators/fetch_op.h
> add PADDLE_MOBILE_CL macro in fetch_op.h

- src/operators/kernel/cl/depthwise_conv_kernel.cpp
- src/operators/kernel/cl/fetch_kernel.cpp
> fix compilation problem

- src/operators/math/depthwise_conv_3x3.cpp
fix compile issues in deepwise 3*3
> fix compile issues in deepwise 3*3 

- CMakeLists.txt
make cpu config as default to avoid of user's confusing #1174
> make cpu config as default to avoid of user's confusing(#1174)

- src/operators/fusion_conv_add_relu_op.h
- src/operators/math/softmax.cpp
- tools/android-debug-script/push2android.sh
> repair bug of softmax and conv_add_relu op

- src/framework/operator.cpp
> modify operator.cpp
